In [1]:
import tensorflow as tf

X = tf.placeholder("float", [None,2])# 2 featuress
Y = tf.placeholder("float", [None,2]) # 2 classes

W_H = tf.Variable(tf.random_normal([2,2], stddev=0.01)) #Hidden layer weights
#b1 = tf.Variable(tf.random_normal([1]))
#W_O = tf.Variable(tf.random_normal([3,2], stddev=0.01))  # output layer weights
#b2 = tf.Variable(tf.random_normal([1]))

#h = tf.nn.sigmoid(tf.matmul(X, W_H))
Y_pred = tf.matmul(X,W_H)

In [2]:
dataset = [[2.7810836,2.550537003,0],
[1.465489372,2.362125076,0],
[3.396561688,4.400293529,0],
[1.38807019,1.850220317,0],
[3.06407232,3.005305973,0],
[7.627531214,2.759262235,1],
[5.332441248,2.088626775,1],
[6.922596716,1.77106367,1],
[8.675418651,-0.242068655,1],
[7.673756466,3.508563011,1]]
XOR_data= [[0,0,0],
          [0,1,1],
          [1,0,1],
          [1,1,0]]
train_X=[]
train_Y=[]

for row in dataset:
    train_X.append(row[0:-1])
    train_Y.append(row[-1])

In [3]:
import numpy as np
train_X=np.array(train_X)
train_Y=np.array(train_Y)
test_X=train_X
test_Y=train_Y

In [4]:
print(train_Y)
train_Y.shape

[0 0 0 0 0 1 1 1 1 1]


(10,)

In [5]:
# convert the data 

temp = train_Y.shape
train_Y = train_Y.reshape(temp[0], 1)
train_Y = np.concatenate((1-train_Y, train_Y), axis=1)

temp = test_Y.shape
test_Y = test_Y.reshape(temp[0], 1)
test_Y = np.concatenate((1-test_Y, test_Y), axis=1)

In [6]:
print(train_Y)
train_Y.shape

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]


(10, 2)

In [7]:
cost=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=Y_pred, labels=Y))

In [8]:
optimizer=tf.train.GradientDescentOptimizer(0.05).minimize(cost)

In [9]:
predict_op = tf.argmax(Y_pred, 1)

In [10]:
epochs = 100

with tf.Session() as sess:
    # you need to initialize all variables
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(epochs):
        
        sess.run(optimizer,feed_dict={X : train_X , Y : train_Y})
        
        if epoch % 10 == 0:
            print()
            print('Cost ', sess.run(cost, feed_dict={X : train_X , Y : train_Y}))
            
            print("epoch : {} and accuracy : {}" .format(epoch, np.mean(np.argmax(test_Y, axis=1) ==
                         sess.run(predict_op, feed_dict={X: test_X}))))
            
            print("testing labels for test data")
            print(sess.run(predict_op, feed_dict={X: test_X}))


Cost  0.588429
epoch : 0 and accuracy : 0.5
testing labels for test data
[1 1 1 1 1 1 1 1 1 1]

Cost  0.362094
epoch : 10 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.267025
epoch : 20 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.21321
epoch : 30 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.178181
epoch : 40 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.15342
epoch : 50 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.134925
epoch : 60 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.120549
epoch : 70 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.109035
epoch : 80 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]

Cost  0.0995931
epoch : 90 and accuracy : 1.0
testing labels for test data
[0 0 0 0 0 1 1 1 1 1]
